site_name: Documentação - Modelo Agrometeorológico Espectral
nav:
    - Apresentação: index.md
    - Modelo de penalização: modelo.md
    - Dados: dados.md
    - Análises: analises.md

theme: readthedocs